server:
  port: 8081

spring:
  application:
    name: user-management-core

keycloak:
  url: http://localhost:8080
  realm: opex
  client-id: "opex-admin"
  client-secret: "**********"
  google-client-id: ${GOOGLE_CLIENT_ID}

otp:
  url: http://localhost:8081