version: '3.8'
services:
  vault-ui:
    ports:
      - "8001:8000"
  consul:
    ports:
      - "8501:8500"
      - "8301:8300"
      - "8601:8600"
  postgres-accountant:
    ports:
      - "5442:5432"
  postgres-eventlog:
    ports:
      - "5443:5432"
  postgres-auth:
    ports:
      - "5444:5432"
  postgres-wallet:
    ports:
      - "5445:5432"
  postgres-api:
    ports:
      - "5446:5432"
  postgres-bc-gateway:
    ports:
      - "5447:5432"
  postgres-referral:
    ports:
      - "5448:5432"
  akhq:
    ports:
      - "10101:8080"