version: '3.8'
services:
  zookeeper:
    user: "root"
  kafka-1:
    user: "root"
  kafka-2:
    user: "root"
  kafka-3:
    user: "root"
  vault:
    ports:
      - "8200:8200"
  consul:
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8600:8600"
  redis:
    ports:
      - "6379:6379"
  redis-cache:
    ports:
      - "6380:6379"
  akhq:
    ports:
      - "127.0.0.1:10100:8080"
  postgres-otp:
    ports:
      - "127.0.0.1:5462:5432"
  accountant:
    ports:
      - "127.0.0.1:8089:8080"
      - "127.0.0.1:1045:5005"
  eventlog:
    ports:
      - "127.0.0.1:8090:8080"
  matching-engine:
    ports:
      - "127.0.0.1:8092:8080"
      - "127.0.0.1:1046:5005"
  matching-gateway:
    ports:
      - "127.0.0.1:8093:8080"
      - "127.0.0.1:1047:5005"
  auth:
    ports:
      - "127.0.0.1:8083:8080"
      - "127.0.0.1:1048:5005"
  wallet:
    ports:
      - "127.0.0.1:8091:8080"
      - "127.0.0.1:1049:5005"
  market:
    ports:
      - "127.0.0.1:8096:8080"
      - "127.0.0.1:1056:5005"
  api:
    ports:
      - "127.0.0.1:8094:8080"
      - "127.0.0.1:1050:5005"
  bc-gateway:
    ports:
      - "0.0.0.0:8095:8080"
      - "127.0.0.1:1052:5005"
  otp:
    ports:
      - "0.0.0.0:8097:8080"
      - "127.0.0.1:1053:5005"
