server.port: 8090
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
       group-id: eventlog
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_eventlog
    username: opex
    password: hiopex
    initialization-mode: always