scrape_configs:
  - job_name: "Kafka cluster"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "kafka-1:1234"
          - "kafka-2:1234"
          - "kafka-3:1234"
        labels:
          env: "dev"
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'accountant:8080' ]
        labels:
          application: 'Accountant'
      - targets: [ 'wallet:8080' ]
        labels:
          application: 'Wallet'
      - targets: [ 'api:8080' ]
        labels:
          application: 'API'
      - targets: [ 'bc-gateway:8080' ]
        labels:
          application: 'Blockchain Gateway'
      - targets: [ 'captcha:8080' ]
        labels:
          application: 'Captcha'
      - targets: [ 'market:8080' ]
        labels:
          application: 'Market'
      - targets: [ 'eventlog:8080' ]
        labels:
          application: 'Eventlog'
      - targets: [ 'matching-engine:8080' ]
        labels:
          application: 'Matching Engine'
      - targets: [ 'matching-gateway:8080' ]
        labels:
          application: 'Matching Gateway'
      - targets: [ 'storage:8080' ]
        labels:
          application: 'Storage'
      - targets: [ 'auth:8080' ]
        labels:
          application: 'Auth'
      - targets: [ 'websocket:8080' ]
        labels:
          application: 'Websocket'