spring:
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
  redis:
    host: ${REDIS_HOST}
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/opex_api
    username: opex
    password: hiopex
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

app:
  matching-gateway:
    url: lb://opex-gateway
