name: build opex
on:
  push:
   branches:
   - main
jobs:
  jenkinsJob:
    name: build opex new version
    runs-on: ubuntu-latest
    steps:
    - name: trigger opex build job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_URL }}
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "opex-build-job"
